---
# This playbook prints a simple debug message
- name: Echo
  hosts: localhost
  connection: local
  vars:
    mymessage: "hello"

  tasks:
    - name: Print debug message
      debug:
        msg: "{{ mymessage }}"
